version: '3.2'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        user: 1000:1000
        volumes:
            - ./mongod.conf:/etc/mongod.conf
            - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
            - ./.docker/mongodb/data/db/:/data/db/
            - ./.docker/mongodb/data/log/:/var/log/mongodb/
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
            MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
            MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
        ports:
            - "27017:27017"
        command: ["-f", "/etc/mongod.conf"]
    # getter:
    #     build: ./getter
    #     volumes:
    #         - ./getter/src:/usr/src/app
